### ISSUE TITLE
Way to force rebuild of layer

### ISSUE THREAD

**Issue by RDIL** [csweichel/dazzle#5]
It would be cool if you can force a named layer to rebuild even if the SHA is the same.  This is so gitpod workspace images can be rebuilt without adding things like echo statements just to bump unpinned versions. 

cc @32leaves

**Comment by 32leaves** [comment]
For CI builds (like [gitpod-io/workspace-full](https://github.com/gitpod-io/workspace-images/blob/master/full/Dockerfile)) I'm afraid the only way to trigger a rebuild would be a change in the layer (e.g. incrementing `ENV trigger_rebuild 1`).

For local dev, we could introduce a CLI flag like `--force-layer-build=lang/go`. Would that suite your needs?

**Comment by RDIL** [comment]
The env var works.  Thanks.
